executor: return error message from the journal
Previously, the output of the systemd unit was only reported in bootc
operator. Now, it is returned as part of the error when bootc switch
fails.

The output for the systemd unit is quite verbose, so we filter for the
lines containing the errors tag. The full output will be reduced from:
        bootc stage failed: running bootc switch: Started bootc-operator-switch.service - [systemd-run] /usr/bin/bootc switch ghcr.io/bootc-dev/bink/node@sha256:9ce7d6d15b8558c226b4c41f3b27bf1722897b0c8a66c7a84a2877bca8d049f7.
        Switching from image ghcr.io/bootc-dev/bink/node:v1.35-fedora-44 to ghcr.io/bootc-dev/bink/node@sha256:9ce7d6d15b8558c226b4c41f3b27bf1722897b0c8a66c7a84a2877bca8d049f7
        Fetching ostree-unverified-registry:ghcr.io/bootc-dev/bink/node@sha256:9ce7d6d15b8558c226b4c41f3b27bf1722897b0c8a66c7a84a2877bca8d049f7
        error: Switching: Switching (ostree): Preparing import: Fetching manifest: Target image does not have ostree.bootable label
        bootc-operator-switch.service: Main process exited, code=exited, status=1/FAILURE
        bootc-operator-switch.service: Failed with result 'exit-code'.
        bootc-operator-switch.service: Consumed 210ms CPU time over 1.111s wall clock time, 155.2M memory peak.: exit status 1
to

      'bootc stage failed: running bootc switch: error: Switching: Switching
        (ostree): Preparing import: Fetching manifest: Target image does not have
        ostree.bootable label: exit status 1'

The full message in any case is present in the bootc daemon logs.

Assisted-by: AI
Signed-off-by: Alice Frosi <afrosi@redhat.com>